name: Check PR

on:
  pull_request_target:
    types: [opened]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{github.event.number}}

    steps:
      - name: Get PR info
        id: pr_info
        run: |
          content=`curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=json::$content"
      - name: Check draft
        if: "${{!startsWith(fromJson(steps.pr_info.outputs.json).title,'WIP') && !fromJson(steps.pr_info.outputs.json).draft}}"
        run: |
          echo "Not draft"
      - run: |
          echo "${{steps.pr_info.outputs.json}}"
#echo "${{fromJson(steps.set_var.outputs.json).version}}"
